### ISSUE TITLE
Receiving only the last background push silent notification.

### ISSUE THREAD

**Issue by Natanael1234** [phonegap/phonegap-plugin-push#1152]
### Expected Behaviour
Receive multiple background silent push notifications.
### Actual Behaviour
Receiving only the last background push silent notification.

#### Steps to Reproduce 
Send two or more silent background messages while the app is closed.
Open the app. 
The last notification is received by the on receive listener.

#### Platform and Version
Android 5.1.1/6.0
#### (Android) What device vendor  
Google
#### Cordova CLI version and cordova platform version

    cordova --version                                    6.2.0
    cordova platform version android                     5.1.1

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   1.7.4

#### Sample Push Data Payload
```
{
                "delay_while_idle": true,
                "priority": "high",
               
                "data": {
                    "content-available": "1",                   
                    "notId": Date.now(),
                    "silenttitle": 'some title',
                    "silentmessage": 'some message'
                }
}
```

**Comment by macdonst** [comment]
@Natanael1234 good scenario, thanks for the bug report.

**Comment by anjali14garg** [comment]
any updates on this issue

**Comment by macdonst** [comment]
@anjali14garg yup, it was fixed yesterday by #1272. Grab the latest code from the github url or wait for the next version of the plugin.

**Comment by anjali14garg** [comment]
Hello Simon,

I am still facing the problem with the plugin version 1.8.3. With the
update  i am getting 2 notification and only after clicking on every
notification on shades.

I hope in this all the latest changes are present done by you , or I should
take pull from github in plugin.

Steps to Reproduce
Kill application and send 3 notification one after the another and then
open the application using notification in shades. You will get the
notification on which you have clicked . But it will happen only for 2
notification. When you click on 2nd notification the 3rd one will go
automatically (lost).

Note notifications are not in single tray.

Please help me to solve. I am stucked.

Thanking you
Best Regards
Anjali
