### ISSUE TITLE
PushPlugin compile fails exitcode 1

### ISSUE THREAD

**Issue by ChristopheDaVinci** [phonegap/phonegap-plugin-push#137]
I've been wrestling with a bug several days now and i can't get it to work whatever i try or do. I have created [a stackoverflow post](http://stackoverflow.com/questions/32568078/pushplugin-compile-fails-exitcode-1) describing the details of the problem. Today i threw in the towle and used the older version of the phonegap pushplugin and it works just fine. But i really would like to know if anybody is experiencing the same problem and if there is a workaround?

**Comment by macdonst** [comment]
@ChristopheDaVinci I just merged a fix for the missing symbols error. 

Regarding the minimum Android version, you'll either need to create your project with the version 5+ CLI or update your project to the new min sdk.

**Comment by ChristopheDaVinci** [comment]
Thank you verry much, works like a charm! :+1:

**Comment by jokabuyasina** [comment]
still not working for me can you please share your project or something i can follow up on.

**Comment by jokabuyasina** [comment]
@ChristopheDaVinci  @macdonst  can you please make a new project with the plugin working and send to me please... thank you

**Comment by nom-user-valide** [comment]
Same for me, so I downloaded the 1.2.2 version and imported it in Visual Studio, and worked

**Comment by macdonst** [comment]
@jokabuyasina are you still seeing the same issue described in the above stack overflow post or is it something different?

**Comment by jokabuyasina** [comment]
@macdonst  it something different..can you help me with a working project man, i know that your are very busy but do me the favour please.

**Comment by macdonst** [comment]
@jokabuyasina You are not giving me much to go on. I'm closing this issue as it has been resolved. Please try using the example/www as a basis for your app and if that doesn't work please open a new issue with details.
