### ISSUE TITLE
Custom sounds not playing on Android 8 devices

### ISSUE THREAD

**Issue by emc2spider** [phonegap/phonegap-plugin-push#2017]
### Expected Behaviour
When a push notification arrives and a custom sound is specified it should play on the device regardless if the app is closed or in the background.
This was also tested on a Sony Xperia Z1 Compact running Android 5.1.1 and the same app build with the same conditions and same payload structure plays the sound just fine.

### Actual Behaviour
The push notification arrives but no sound is played even when the sound filename is specified on the notification payload and the sound file is in the res/raw folder.

### Reproduce Scenario (including but not limited to)
Send a push notification to the app running on an Android 8 device, the app must be either closed or in the background.

#### Steps to Reproduce 
* Install app
* Register push notification handlers
* Minimise app
* Send push notification

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Android 8.0.0

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)
Nexus 6P

#### Cordova CLI version and cordova platform version

    cordova --version =  7.0.1
    cordova platform version android   =  6.3.0

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push  =  2.0.0

#### Sample Push Data Payload
```{
 "sound": "standard",
 "title": "Test",
 "message": "New job",
 "additionalData": {
  "content-available": "1",
  "summaryText": "There are %n% notifications",
  "style": "inbox",
  "internal_data": {
   "code": "NEW_JOB"
   "timeout": 30,
   "expires": "2017-10-17 17:09:41"
  },
  "coldstart": true,
  "foreground": false
 }
}```

**Comment by macdonst** [comment]
@emc2spider grab some logs for me `adb logcat | grep Push` when you send the notification to the device.

**Comment by emc2spider** [comment]
Hi @macdonst sure thing, I've just ran this test:

```
10-18 10:25:55.231 31342  1193 D Push_FCMService: onMessage - from: 709460980589
10-18 10:25:55.232 31342  1193 D Push_FCMService: normalize extras
10-18 10:25:55.232 31342  1193 D Push_FCMService: key = soundname
10-18 10:25:55.232 31342  1193 D Push_FCMService: replace key soundname with sound
10-18 10:25:55.232 31342  1193 D Push_FCMService: key = content-available
10-18 10:25:55.233 31342  1193 D Push_FCMService: replace key content-available with content-available
10-18 10:25:55.233 31342  1193 D Push_FCMService: key = summaryText
10-18 10:25:55.233 31342  1193 D Push_FCMService: replace key summaryText with summaryText
10-18 10:25:55.234 31342  1193 D Push_FCMService: no locale found for key = summaryText, error Value There of type java.lang.String cannot be converted to JSONObject
10-18 10:25:55.234 31342  1193 D Push_FCMService: key = data
10-18 10:25:55.235 31342  1193 D Push_FCMService: extracting nested message data from key = data
10-18 10:25:55.235 31342  1193 D Push_FCMService: key = style
10-18 10:25:55.235 31342  1193 D Push_FCMService: replace key style with style
10-18 10:25:55.235 31342  1193 D Push_FCMService: key = title
10-18 10:25:55.235 31342  1193 D Push_FCMService: replace key title with title
10-18 10:25:55.236 31342  1193 D Push_FCMService: no locale found for key = title, error Value Gophr of type java.lang.String cannot be converted to JSONObject
10-18 10:25:55.236 31342  1193 D Push_FCMService: key = message
10-18 10:25:55.236 31342  1193 D Push_FCMService: replace key message with message
10-18 10:25:55.236 31342  1193 D Push_FCMService: no locale found for key = message, error Value New of type java.lang.String cannot be converted to JSONObject
10-18 10:25:55.236 31342  1193 D Push_FCMService: key = gophr_data
10-18 10:25:55.236 31342  1193 D Push_FCMService: replace key gophr_data with gophr_data
10-18 10:25:55.237 31342  1193 D Push_FCMService: background
10-18 10:25:55.242 31342  1193 D Push_FCMService: message =[New job for you!]
10-18 10:25:55.242 31342  1193 D Push_FCMService: title =[Gophr test]
10-18 10:25:55.242 31342  1193 D Push_FCMService: contentAvailable =[1]
10-18 10:25:55.242 31342  1193 D Push_FCMService: forceStart =[null]
10-18 10:25:55.242 31342  1193 D Push_FCMService: create notification
10-18 10:25:55.243 31342  1193 E Push_FCMService: Number format exception - Error parsing notId: s == null
10-18 10:25:55.247 31342  1193 D Push_FCMService: stored icon=notification
10-18 10:25:55.248 31342  1193 D Push_FCMService: stored iconColor=black
10-18 10:25:55.248 31342  1193 D Push_FCMService: stored sound=true
10-18 10:25:55.248 31342  1193 D Push_FCMService: stored vibrate=true
10-18 10:25:55.248 31342  1193 D Push_FCMService: using icon from plugin options
10-18 10:25:55.248 31342  1193 D Push_FCMService: android.resource://it.gophr.courier/raw/standard
10-18 10:25:55.261 31342  1193 D Push_FCMService: create actions: with in-line
10-18 10:25:55.266 31342  1193 D Push_FCMService: app is not running and content available true
10-18 10:25:55.266 31342  1193 D Push_FCMService: send notification event
10-18 10:25:55.266 31342  1193 D Push_Plugin: convert extras to json
10-18 10:25:55.266 31342  1193 D Push_Plugin: key = content-available
10-18 10:25:55.266 31342  1193 D Push_Plugin: key = summaryText
10-18 10:25:55.266 31342  1193 D Push_Plugin: key = sound
10-18 10:25:55.266 31342  1193 D Push_Plugin: key = style
10-18 10:25:55.266 31342  1193 D Push_Plugin: key = title
10-18 10:25:55.266 31342  1193 D Push_Plugin: key = message
10-18 10:25:55.266 31342  1193 D Push_Plugin: key = gophr_data
10-18 10:25:55.267 31342  1193 D Push_Plugin: key = coldstart
10-18 10:25:55.267 31342  1193 D Push_Plugin: key = foreground
10-18 10:25:55.267 31342  1193 V Push_Plugin: extrasToJSON: {"sound":"standard","title":"Gophr test","message":"New job for you!","additionalData":{"content-available":"1","summaryText":"There are %n% notifications","style":"inbox","gophr_data":{"code":"NEW_JOB","job_id":"4368","timeout":30,"expires":"2017-10-18 10:26:20","notification_id":757204},"coldstart":true,"foreground":false}}
10-18 10:25:55.274 31342 31506 V Push_Plugin: execute: action=finish

**Comment by emc2spider** [comment]
Also, I've noticed now that it says on the logs `Push_FCMService` however we're using GCM. Will this make a difference?

**Comment by dmnkgrc** [comment]
Same issue, running on a Google Pixel :( 

Version 2.1.0 of the plugin

**Comment by nprail** [comment]
I've got the same problem with Android 8.0.0 and `phonegap-plugin-push` 2.1.0. My logs are pretty much the same as @emc2spider's.

**Comment by macdonst** [comment]
@emc2spider no, that's just the name of the class that handles the incoming push data.

**Comment by macdonst** [comment]
@emc2spider @nprail @dmnkgrc can I get an example of the payload you are sending? It should look like the following:

```
{
    "registration_ids": ["my device id"],
    "data": {  // note: the payload is in data, not notification
    	"title": "Sound Test",
    	"message": "Loaded res/raw",
    	"soundname": "test"
    }
}
```

I can't reproduce your problem and I'm doing it on my Pixel XL running Android 8.

**Comment by emc2spider** [comment]
@macdonst you mean the data as it is sent from our server? Otherwise, I've added the payload on the first message. Copying again in case it's easier to find:

######Sample Push Data Payload

```{
 "sound": "standard",
 "title": "Test",
 "message": "New job",
 "additionalData": {
  "content-available": "1",
  "summaryText": "There are %n% notifications",
  "style": "inbox",
  "internal_data": {
   "code": "NEW_JOB"
   "timeout": 30,
   "expires": "2017-10-17 17:09:41"
  },
  "coldstart": true,
  "foreground": false
 }
}```

**Comment by macdonst** [comment]
@emc2spider that looks like the payload that you would receive in the `on('notification')` handler. What I mean is what do you send to the push service. Something like: 

```
{
    "registration_ids": ["my device id"],
    "data": {
    	"title": "Default",
    	"message": "Plays default notification sound",
    	"soundname": "default"
    }
}
```

**Comment by emc2spider** [comment]
@macdonst Yeah, that was my question. I have retrieved the server data now:

```
{
  "registration_ids": ["cGGuMfFth-DEVICE-ID-xLY7kHGfSb0"],
  "priority": "high",
  "data": {
    "title": "Test",
    "message": "New job",
    "style": "inbox",
    "summaryText": "There are %n% notifications",
    "data": "{"code":"NEW_JOB","timeout":30,"expires": "2017-11-13 14:19:41"}",
    "gophr_data": "{"code":"NEW_JOB","timeout":30,"expires": "2017-11-13 14:19:41"}",
    "content-available": "1",
    "soundname": "standard"
  }
}

**Comment by macdonst** [comment]
@emc2spider oddly enough the payload looks fine to me. One quick test though, can you try sending without priority?

**Comment by emc2spider** [comment]
Hi @macdonst, sorry I kinda dropped the ball on this one. There is no difference with or without priority in the payload.

**Comment by emc2spider** [comment]
I have upgraded to the plugin version 2.1.2 and still no custom sounds on the Android 8 test device. We've since experimented with channels and the only constant issue is the lack of sound.

**Comment by ruben82** [comment]
Any news about this issue??

**Comment by netomia** [comment]
Same issue on my Nexus 6P with Android 8.1 and plugin version 2.1.2. Latest Cordova, cordova-android, Gradle, Android SDKs, Java, npm.

**Comment by jholzer-cciq** [comment]
@macdonst I was also able to reproduce this issue today. I deployed the same app to a Google Pixel running Android 8.1, and a Nexus 7 tablet running Android 6.0.1, and the custom sound played great on the Nexus 7 (Android 6.0.1), but the Pixel (Android 8.1.0) played the system default notification sound instead.

My app is using the following versions of Cordova CLI, cordova-android, and phonegap-plugin-push:
```
Cordova CLI = 8.0.0
cordova platform version android = 7.0.0
phonegap-plugin-push = 2.1.2
```

The JSON payload I'm sending from the server side looks like this:
```
{
  "registration_ids": ["..."],
  "data": {
    "message": "This is a test",
    "title": "Test",
    "soundname": "alarm_1"
  }
}
```

There is a file named alarm_1.wav in my android project/platform folder, located at `app/src/main/res/raw/alaram_1.wav`

**Comment by jholzer-cciq** [comment]
The issue for me ended up being related to notification channels, which are a new concept in Android 8.0+. I ended up creating my own notification channel, which I associated with my custom sound, and then was able to get the custom sound to play when a notification arrived (code snippets below). If you do not explicitly create a channel, the plugin will register a default channel for you, which uses the system default notification sound.

It appears that when a sound is associated with a notification channel, that it will override a sound that is set for a specific message (i.e. using the "soundname" field in JSON payload from server). 

The plugin does provide an API call to create a notification channel. I'm creating one just prior to calling `PushNotification.init`, with code similar to the following:
```
var channelId = 'reminders';

PushNotification.createChannel(
    function() { console.log("Successfully created notification channel: " + channelId); },
    function() { console.log("Failed while attempting to create notification channel: " + channelId); },
    {
        id: channelId,
        description: "Reminders",
        importance: 4, // high importance
        sound: "alarm_1"  // plays alarm_1.wav in the res/raw folder
    }
);
```

The JSON payload I'm sending from the server includes an "android_channel_id" field, which tells the plugin which channel to associate the notification with. It looks something like the following:
```
{
  "registration_ids": ["..."],
  "data": {
    "message": "Test message",
    "title": "Reminder",
    "soundname": "alarm_1",  // for Android versions < 8.0 (API Level < 26)
    "android_channel_id": "reminders",
  }
}
```

**Comment by emc2spider** [comment]
@jholzer-cciq I've added the channels as well, but I need different notification sounds depending on the message contents, however the type of message is still the same, so it doesn't make much sense for us to have so many different channels for the same type of messages that vary only in one characteristic.
I'm running a test with a fixed custom sound for all messages and see how that goes, thanks for the idea 👍

**Comment by jholzer-cciq** [comment]
@emc2spider Based on [Android API documentation](https://developer.android.com/reference/android/app/NotificationChannel.html), it seems like it should be possible to change the channel sound prior to posting a message (see the NotificationChannel.setSound method). This would require changes to the Android side of the plug in however.

For better or worse, it seems like Google wants you to have a bunch of different channels. There's no question they're pushing people away from setting the sound on a message-by-message basis. In the latest Android API, all the overloads of the setSound method in the [Notification.Builder class](https://developer.android.com/reference/android/app/Notification.Builder.html) have been deprecated, and replaced with similar methods in the [NotificationChannel class](https://developer.android.com/reference/android/app/NotificationChannel.html).

**Comment by HugoHeneault** [comment]
Any updates on this here? 😦

**Comment by jholzer-cciq** [comment]
@HugoHeneault If you're just looking to play a sound when your notification arrives in Android 8.0+, then you should use the plugin's `PushNotification.createChannel` method to create a notification channel when your app starts up (see example from earlier in this thread). Just specify the sound resource when configuring the channel. You just set the "android_channel_id" in the data section of your message payload. For supporting multiple sounds, just use multiple channels.

If you need to support Android versions prior to 8.0, then you'll need to continue to specify the sound name in the message payload as well.

If you're looking to do what emc2spider wants, playing multiple sounds using a single channel, then that would require modifications to the plugin source.

**Comment by ruben82** [comment]
Hi, 
I created a new channel in my application
```
 this.push.createChannel({
      id: 'alert',
      description: "alert",
      importance: 4
    }).then(res => {
      console.debug("PushServiceProvider::configNotification - Channel created");
    }).catch(e => {
      console.error('PushServiceProvider::configNotification - Channel did not created -> ' + JSON.stringify(e));
    });
```

Added a .wav called alert in my res/raw

Put this in my payload
```

"data":{  
      "body":"Ciao",
      "message":"Testo del messaggio della notifica",
      "content-available": 1,
      "sound": "alarm.wav",
      "android_channel_id": "alert"
   }
```

No way to make it works

**Comment by jholzer-cciq** [comment]
@ruben82 Try changing your message payload slightly:
- Change the `sound` property to `soundname`
- **Do not** include the .wav file extension when specifying the sound. Just use `alarm` (instead of alarm.wav)

**Comment by ruben82** [comment]
@jholzer-cciq thanks for reply me.
I try your advice, but no way. It is not working.
I cant understand your last sentence... I Create a channel and then make Push.init. I cannot find some complete example about this argument.
Anyway I notice a weird things: When I create a new channel and enter in then function, I tried to check the channels list to find out my brend new channel, but I cannot find it. Is it right this behaviour??

**Comment by jholzer-cciq** [comment]
@ruben82 Part of your problem is that you are not specifying a sound for the channel, which you must do for Android 8.0+.

For example, the object you pass to your `createChannel` function should look like this:
```
{
    id: 'alert',
    description: "alert",
    importance: 4,
    sound: "alarm" 
}
```

I was just curious about your `createChannel` method, because it's expecting a Promise object to be returned, and the [PushNotification.createChannel method](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushnotificationcreatechannelsuccesshandler-failurehandler-channel) does not return a Promise. I was just asking if you had written your own code that returns a Promise.

**Comment by ruben82** [comment]
@jholzer-cciq Channel interface  in IONIC 3 does not have sound as attribute as [you can see](https://ionicframework.com/docs/native/push):

```
export interface Channel {
    id: string;
    description: string;
    importance: Priority;
}

```
So maybe ionic plugin is not aligned to cordova plugin...

**Comment by jholzer-cciq** [comment]
@ruben82 Sorry. I had no idea you were using Ionic!

It looks like you are correct. The Ionic push plugin and cordova plugin do not seem to be in sync. In Android 8.0+ (Oreo), the notification sound must be defined as part of the channel.

Putting the sound in the message payload will only work for users that are on Android 7 (Nougat) or below.

I've never used Ionic. Is there any way you can use the cordova plugin directly?

**Comment by HugoHeneault** [comment]
@ruben82 The ionic team is not big enough to maintain all their plugin up-to-date against all the cordova plugins. 
In my team, we prefer using cordova plugins instead of the ionic ones when the plugins are updated very often. It's not a big markup change 🙂

**Comment by ruben82** [comment]
Hi @HugoHeneault I think you business choice was the rightest one..

**Comment by dmnkgrc** [comment]
Hi @ruben82, I actually made a PR to fix this in the Ionic plugin, but it has not been reviewed yet for the reason @HugoHeneault mentioned

**Comment by fabledfoe** [comment]
After spending weeks trying to figure this particular issue out, I've realized that custom notification sounds DO play when the 'sound' key is present in the 'notification' object, but they do NOT play when the 'sound' key is present in the 'data' object.  We've been using data exclusively, so the thought never crossed my mind to change it.  

The only real issue with changing to notification is we lose a lot of meta data like images and the plugin appears to process both objects individually as 2 separate messages when both 'notification' and 'data' are present.

Btw, these results were based on a Pixel XL running 8.1.0

**Comment by barmarko27** [comment]
Hi,
I have a problem with channels definitions in ionic2.
`var channelId = 'reminders';

    PushNotification.createChannel(
      function() { console.log("Successfully created notification channel: " + channelId); },
      function() { console.log("Failed while attempting to create notification channel: " + channelId); },
      {
          id: channelId,
          description: "Reminders",
          importance: 4, // high importance
          sound: "sounddefault"  // plays alarm_1.wav in the res/raw folder
      }
  );

    let push = PushNotification.init({
      android: {
        senderID: 'XXXXXXXXX',
        forceShow: true
      },
      ios: {
        alert: "true",
        badge: true,
        sound: 'true'
      },
      windows: {}
    });`

When i try to emulate the app, cordova return this error: 

> **_Property 'createChannel' does not exist on type 'PushNotificationStatic'._**

Someone has the same error?

Thanks

**Comment by TeamFeuerwehr** [comment]
@iranicus 

I've found a solution. 

this.push.createChannel({
     id: "testchannel7",
     description: "asdf",
    **sound: 'pulse'**,
     // The importance property goes from 1 = Lowest, 2 = Low, 3 = Normal, 4 = High and 5 = Highest.
     importance: 4,
     vibration: true
    }).then(() => console.log('Channel created'));

You have to set the sound tag in the createChannel function. (Place the sound file in **res/raw/** (In my case pulse.wav))
