### ISSUE TITLE
Can't use Google Maps Plugin w/ Push Plugin

### ISSUE THREAD

**Issue by ehorodyski** [phonegap/phonegap-plugin-push#2614]
### Expected Behaviour
Be able to build for Android with both plugins.

### Actual Behaviour
See log below.

#### Steps to Reproduce 
1. Add Google Maps plugin and Phonegap Push Plugin together in the same project
2. Use `cordova-android@6.4.0` for plugin compatibility purposes.

After reading your documentation, I tried uninstalling and reinstalling the push plugin pointing `FCM_VERSION` to `15.0.1` to match the maps' version, but it does not exist:

```
Could not find com.google.firebase:firebase-messaging:15.0.1.
  Searched in the following locations:
      file:/Applications/android-sdk/extras/m2repository/com/google/firebase/firebase-messaging/15.0.1/firebase-messaging-15.0.1.pom
      file:/Applications/android-sdk/extras/m2repository/com/google/firebase/firebase-messaging/15.0.1/firebase-messaging-15.0.1.jar
      file:/Applications/android-sdk/extras/google/m2repository/com/google/firebase/firebase-messaging/15.0.1/firebase-messaging-15.0.1.pom
      file:/Applications/android-sdk/extras/google/m2repository/com/google/firebase/firebase-messaging/15.0.1/firebase-messaging-15.0.1.jar
      file:/Applications/android-sdk/extras/android/m2repository/com/google/firebase/firebase-messaging/15.0.1/firebase-messaging-15.0.1.pom
      file:/Applications/android-sdk/extras/android/m2repository/com/google/firebase/firebase-messaging/15.0.1/firebase-messaging-15.0.1.jar
      https://jcenter.bintray.com/com/google/firebase/firebase-messaging/15.0.1/firebase-messaging-15.0.1.pom
      https://jcenter.bintray.com/com/google/firebase/firebase-messaging/15.0.1/firebase-messaging-15.0.1.jar
      https://maven.google.com/com/google/firebase/firebase-messaging/15.0.1/firebase-messaging-15.0.1.pom
      https://maven.google.com/com/google/firebase/firebase-messaging/15.0.1/firebase-messaging-15.0.1.jar
      https://repo1.maven.org/maven2/com/google/firebase/firebase-messaging/15.0.1/firebase-messaging-15.0.1.pom
      https://repo1.maven.org/maven2/com/google/firebase/firebase-messaging/15.0.1/firebase-messaging-15.0.1.jar
```

...etc

Any help would be appreciated.

#### Cordova CLI version and cordova platform version

    8.1.2
    6.4.0

#### Plugin version

    2.1.3 # Push
    2.4.6 # cordova-plugin-googlemaps

#### Logs taken while reproducing problem

```
> cordova run android
ANDROID_HOME=/Applications/android-sdk/
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home
Subproject Path: CordovaLib
Configuration 'compile' in project ':' is deprecated. Use 'implementation' instead.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_1kl8wwhxgl2y8uycmi6hq7q3g.run(/Users/xxx/Projects/app/platforms/android/build.gradle:143)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)

registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
publishNonDefault is deprecated and has no effect anymore. All variants are now published.

:preBuild
 UP-TO-DATE

:CordovaLib:preBuild
 UP-TO-DATE
:CordovaLib:preDebugBuild
 UP-TO-DATE
:CordovaLib:checkDebugManifest

:CordovaLib:processDebugManifest

:preDebugBuild

:CordovaLib:compileDebugAidl

:compileDebugAidl

:CordovaLib:packageDebugRenderscript
 NO-SOURCE
:compileDebugRenderscript

:checkDebugManifest
:generateDebugBuildConfig
:prepareLintJar UP-TO-DATE

:generateDebugResValues

:generateDebugResources

:processDebugGoogleServices

Found com.google.android.gms:play-services-maps:15.0.1, but version 11.6.2 is needed for the google-services plugin.

Found com.google.android.gms:play-services-location:15.0.1, but version 11.6.2 is needed for the google-services plugin.
:processDebugGoogleServices
FAILED

FAILURE: Build failed with an exception.


* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.6.2.


* Try:
Run with --stacktrace
 option to get the stack trace. Run with --info or --debug
 option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
11 actionable tasks: 10 executed, 1 up-to-date
/Users/xxx/Projects/app/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.6.2.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
[ERROR] An error occurred while running cordova run android (exit code 1).
```

**Comment by jcesarmobile** [comment]
sorry, this is fixed but latest version of the plugin requires cordova-android 7.1.x.

**Comment by ehorodyski** [comment]
@jcesarmobile - Yikes! That's upsetting. Glad to know I won't run into this issue in the near-future, once the team and I figure out what to do about this pesky plugin dependency.

**Comment by ehorodyski** [comment]
@jcesarmobile - Still getting this issue, even after upgrading cordova-android to 7.1.2
