### ISSUE TITLE
Uncaught ReferenceError: PushNotification is not defined 

### ISSUE THREAD

**Issue by sulthanallaudeen** [phonegap/phonegap-plugin-push#271]
I am getting `Uncaught ReferenceError: PushNotification is not defined ` whenever i run the example..

If i install this plugin 

cordova plugin add phonegap-plugin-push

or 

cordova plugin add https://github.com/phonegap/phonegap-plugin-push

I can't able to run the app itself 

This is the line i am getting error

`var push = PushNotification.init({`

What is the problem and how can i fix this ?

**Comment by sulthanallaudeen** [comment]
Here is the error i got in the command prompt

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.android.support:support-v13:23+
.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v13/maven-me
tadata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v13/
         file:/E:/dummy/adt-bundle-windows-x86_64-20140702/sdk/extras/android/m2
repository/com/android/support/support-v13/maven-metadata.xml
         file:/E:/dummy/adt-bundle-windows-x86_64-20140702/sdk/extras/google/m2r
epository/com/android/support/support-v13/maven-metadata.xml
         file:/E:/dummy/adt-bundle-windows-x86_64-20140702/sdk/extras/google/m2r
epository/com/android/support/support-v13/
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 6.053 secs

C:\Users\anas\newpush\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "C:\Users\anas\newpush\platforms\
android\gradlew cdvBuildDebug -b C:\Users\anas\newpush\platforms\android\build.g
radle -PcdvBuildArch=x86 -Dorg.gradle.daemon=true"
ERROR running one or more of the platforms: Error: cmd: Command failed with exit
 code 1
You may not have the required environment or OS to run this project

**Comment by bmwsedee** [comment]
I encountered this on a computer of one of my colleagues just yesterday,
and it turned out not all dependencies as mentioned in the docs
<https://github.com/phonegap/phonegap-plugin-push#compiling> were installed.
It says to install:

   - Android Support Library version 23 or greater
   - Android Support Repository version 20 or greater
   - Google Play Services version 27 or greater
   - Google Repository version 22 or greater


On Wed, Oct 28, 2015 at 12:52 PM Sulthan Allaudeen <notifications@github.com>
wrote:

> Here is the error i got in the command prompt
>
> FAILURE: Build failed with an exception.
>
>    -
>
>    What went wrong:
>    A problem occurred configuring root project 'android'.
>
>    Could not resolve all dependencies for configuration ':_debugCompile'.
>    Could not find any version that matches
>    com.android.support:support-v13:23+
>    .
>    Searched in the following locations:
>    https://repo1.maven.org/maven2/com/android/support/support-v13/maven-me
>    tadata.xml
>    https://repo1.maven.org/maven2/com/android/support/support-v13/
>    file:/E:/dummy/adt-bundle-windows-x86_64-20140702/sdk/extras/android/m2
>    repository/com/android/support/support-v13/maven-metadata.xml
>    file:/E:/dummy/adt-bundle-windows-x86_64-20140702/sdk/extras/google/m2r
>    epository/com/android/support/support-v13/maven-metadata.xml
>    file:/E:/dummy/adt-bundle-windows-x86_64-20140702/sdk/extras/google/m2r
>    epository/com/android/support/support-v13/
>    Required by:
>    :android:unspecified
>
>    -
>
>    Try:
>    Run with --stacktrace option to get the stack trace. Run with --info
>    or --debug
>    option to get more log output.
>
> BUILD FAILED
>
> Total time: 6.053 secs
>
> C:\Users\anas\newpush\platforms\android\cordova\node_modules\q\q.js:126
> throw e;
> ^
> Error code 1 for command: cmd with args: /s /c
> "C:\Users\anas\newpush\platforms\
> android\gradlew cdvBuildDebug -b
> C:\Users\anas\newpush\platforms\android\build.g
> radle -PcdvBuildArch=x86 -Dorg.gradle.daemon=true"
> ERROR running one or more of the platforms: Error: cmd: Command failed
> with exit
> code 1
> You may not have the required environment or OS to run this project
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-plugin-push/issues/271#issuecomment-151818522>
> .
>
-- 

Met vriendelijke groet,
Ben Sedee
06-20883935

**Comment by sulthanallaudeen** [comment]
So, i want to install all these ?

- Android Support Library version 23 or greater
   - Android Support Repository version 20 or greater
   - Google Play Services version 27 or greater
   - Google Repository version 22 or greater

**Comment by sulthanallaudeen** [comment]
@bmwsedee It worked after installing all those packages ?

**Comment by macdonst** [comment]
@sulthanallaudeen yes, those packages are necessary for this plugin to function properly. Once you install them and re-test please close this issue if it is resolved.

**Comment by sulthanallaudeen** [comment]
@macdonst Ok thanks, i will update and re-test, and will do it accordingly

**Comment by ste5787** [comment]
To solve the problem you have simpy to put the code into 
$ionicPlatform.ready(function() {
      var push = PushNotification.init({
   });

it's right? :)

**Comment by macdonst** [comment]
@ste5787 well yeah, if the user is not waiting for $ionicPlatform.ready() or the `deviceready` event than none of this stuff will work.

**Comment by sulthanallaudeen** [comment]
@ste5787 @macdonst 

Thanks, I have updated the given packages in Android Studio 

And i noted that the function is already inside the `onDeviceReady`

Still i am facing the error.. What could be the issue ? 

onDeviceReady: function() {
		alert('started');
        var push = PushNotification.init({
            "android": {
                "senderID": "762187383962"
            },
            "ios": {"alert": "true", "badge": "true", "sound": "true"}, 
            "windows": {} 
        });
....

I did the again did the fresh install of project and installed the `phonegap-plugin-push` by

`cordova plugin add phonegap-plugin-push`

Then when i try to run 

I am still getting the error 

Here is the Error Trace

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.android.support:support-v13:23+
.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v13/maven-me
tadata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v13/
         file:/E:/dummy/adt-bundle-windows-x86_64-20140702/sdk/extras/android/m2
repository/com/android/support/support-v13/maven-metadata.xml
         file:/E:/dummy/adt-bundle-windows-x86_64-20140702/sdk/extras/google/m2r
epository/com/android/support/support-v13/maven-metadata.xml
         file:/E:/dummy/adt-bundle-windows-x86_64-20140702/sdk/extras/google/m2r
epository/com/android/support/support-v13/
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 6.228 secs

C:\Users\anas\newpush\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "C:\Users\anas\newpush\platforms\
android\gradlew cdvBuildDebug -b C:\Users\anas\newpush\platforms\android\build.g
radle -PcdvBuildArch=arm -Dorg.gradle.daemon=true"
ERROR running one or more of the platforms: Error: cmd: Command failed with exit
 code 1
You may not have the required environment or OS to run this project

What should i do now ?

**Comment by bmwsedee** [comment]
@sulthanallaudeen Just to be sure, but did you install the necessary components in the Android SDK Manager?
Also, does the project compile without the plugin, or do you also get errors when you remove it?

**Comment by sulthanallaudeen** [comment]
@bmwsedee  Yes i have install the necessary components in the Android SDK Manager..

If i remove the plugin and run  the project.. the app is getting installed in the Device but I am getting `PushNotification is not defined` still (I found the error in the chrome::/inspect )

**Comment by ste5787** [comment]
Please try this: whit inspector  opened write "PushNotification" in the console and than press enter key. What happen?

**Comment by bmwsedee** [comment]
@sulthanallaudeen What version of the plugin are you using? Maybe downgrading to 1.3.0 helps (as suggested in #273) or maybe #179 gives any hints?
The error in the console is not surprise really if you remove the plugin, that was just to make sure the error only occurs when including the plugin.

**Comment by macdonst** [comment]
@sulthanallaudeen you have to resolve the problem where the dependency `com.android.support:support-v13:23+` cannot be resolved. Something is not setup correctly in your android environment.

Make sure your $ANDROID_HOME environment variable is set correctly. 

Try opening the project in Android Studio (the platforms/android directory) to see if Android Studio can compile the project. That'll let you know if you've actually got all the dependencies downloaded.

**Comment by sulthanallaudeen** [comment]
@macdonst  The $A\NDROID_HOME is set correctly. 

@bmwsedee @ste5787 Can you tell me whether i am doing correctly.

1. I created a empty cordova project

2. Downloaded the .zip of https://github.com/phonegap/phonegap-plugin-push

and navigated to example->www-> and copied the files 

and pasted the www content to the project's www location 

and i am trying the above steps.. 

Is that correct way ? 

Or should i do something else ?

**Comment by sulthanallaudeen** [comment]
@ste5787 Now i can't even run the cordova project due to the build error . But can you pls say me whether the steps i followed above was correct ?

**Comment by sulthanallaudeen** [comment]
@bmwsedee May i know how to downgrade ? Can you tel me whether the steps i used to do is correct ? Or should i achieve in it some other steps ?

**Comment by bmwsedee** [comment]
@sulthanallaudeen Downgrading can be done by removing the existing plugin (phonegap plugin remove phonegap-plugin-push) and installing the plugin with a specific version (phonegap plugin add phonegap-plugin-push@1.3.0).

I do however think that @macdonst suggestion of opening the project in Android Studio and see if it compiles there will help you the most; your problem seems to be dependency-related.

**Comment by sulthanallaudeen** [comment]
@bmwsedee  Thanks, i will follow it..

Can you tel me whether the steps i am doing is correct ? 

1. I created a empty cordova project

2. Downloaded the .zip of https://github.com/phonegap/phonegap-plugin-push

3. and navigated to example->www-> and copied the files

4. and pasted the www content to the project's www location

5. Tying to built 

Is that correct way ?

**Comment by bmwsedee** [comment]
@sulthanallaudeen If you want a default implementation for handling notifications you will need steps 2-4, if you just want to know whether you can install the plugin and build your project you will only need to do steps 1 and 5 (supposing step 1 includes the installation of the plugin)

**Comment by sulthanallaudeen** [comment]
Yes, I tried 2, 4 .. just wanted to implement the default handling of notifications.

I tried that only .

**Comment by sulthanallaudeen** [comment]
@bmwsedee 


Yes, I tried 2, 4 .. just wanted to implement the default handling of notifications.

I tried that only .

**Comment by macdonst** [comment]
@sulthanallaudeen oh no, that is not the way you install a plugin into a project. This is what you *should* be doing:

1. Create an empty cordova project
2. Add the platform you require, for example `phonegap platform add android`
3. Add the plugin to your project. `phonegap plugin add phonegap-plugin-push`
4. Navigate to example->www-> and copied the files
5. Paste the www content to the project's www location
6. Build

**Comment by sulthanallaudeen** [comment]
@macdonst  Hey, thanks 

I followed the steps provided by you and it is working good 
[I can't able to run in my device directly from my pc, i genereated apk then i installed in mobile and run it, however it is ok for me ]


But the app is displaying only the gcm id and i can't able to find the messages to triiger messages.

What should i do to see it ?

**Comment by sulthanallaudeen** [comment]
@macdonst @bmwsedee 

Thanks for the help..

I can able to run, get the gcm id and alert it. 


When i try to display the GCM. I tried to send push notification like regular android push notification..


Like this 

    $PushMessage = 'test';
    SendNotification($_POST['gcmId'],$PushMessage);


function SendNotification($DevideId,$Message)
{ 
    $PushNotification = new GCM();
    $DevideId = array($DevideId);
    $Message_Decode = $Message;
    $problem = urldecode($Message_Decode);
    $Message = array("price"=>$problem);  
    $result = $PushNotification->send_notification($DevideId, $Message);      
}


class GCM {
    public function send_notification($DevideId, $Message) {
        $url = 'https://android.googleapis.com/gcm/send';
        $fields = array(
            'registration_ids' => $DevideId,
            'data' => $Message
        );
    $headers = array(
             'Authorization: key =myapikey',
            'Content-Type: application/json'
                        );
    $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($fields));
    $result = curl_exec($ch);
    if ($result === FALSE) {
        die('Curl failed: ' . curl_error($ch));
        }
        curl_close($ch);
       }
}

Also changed the 

"senderID": "myprojectnumber"

in the index.js

When i run the app, and send push notification from server side. i am not getting any notification..

What should i do to show the push messages in the app in mobile ?

**Comment by sulthanallaudeen** [comment]
@macdonst 
My device is android, So should i do like this ?

 "ios": {"alert": "true", "badge": "true", "sound": "true"}, "windows": {"alert": "true", "badge": "true", "sound": "true"}

**Comment by sulthanallaudeen** [comment]
@macdonst  Thanks, i followed your instruction and now i can able to run the application and get gcm id.  So, i am closing this one. 

Thanks for the support guys :+1:

**Comment by nadeemkhoury** [comment]
Guys, I still get the same error. although I installed the android SDK components, and follow all the above steps. but nothing has worked for me. PLEASE HELP

**Comment by sulthanallaudeen** [comment]
What error you getting ?

**Comment by nadeemkhoury** [comment]
Thank you sulthan, I fixed my problem by adding this code to my config.xml:
  <platform name="android">
    <preference name="android-minSdkVersion" value="15" />
  </platform>

also, I was debugging in ripple, which will now work unless you debug it on real device. 

Thank you so much.

**Comment by yossale** [comment]
@nadeemkhoury  can you share which code you added to your config.xml? I'm still having the same problem

**Comment by nadeemkhoury** [comment]
<platform name="android">
    <preference name="android-minSdkVersion" value="15"/>
 </platform> 

this one my friend.

**Comment by nadeemkhoury** [comment]
```
<platform name="android">
    <preference name="android-minSdkVersion" value="15"/>
 </platform>
```

this code my friend.

**Comment by fredgalvao** [comment]
@nadeemkhoury  do you have the crosswalk plugin installed on your project? The solution proposed by you doesn't make sense unless you do, as that's a pretty common  crosswalk issue.

**Comment by nadeemkhoury** [comment]
hey bro @fredgalvao, No I don't have crosswalk plugin. I think the main problem was debugging using ripple, when I test it on device it works smoothly. but also the code that I had has a role in fixing my issue.

**Comment by yossale** [comment]
@nadeemkhoury  it worked, thanks!

**Comment by sekhar-ashwin** [comment]
Make Sure that you include right cordova.js and cordova_plugins.js file.

**Comment by hungca** [comment]
Remove ng-app in index.html and put this http://stackoverflow.com/questions/21556090/cordova-angularjs-device-ready.
your app controller/factory/service will run after device ready and PushNotification will be available

**Comment by Toomavic** [comment]
Hello everyone:

I tried to install fresh copy of push notification. Previously I installed deprecated version from [here ](https://github.com/phonegap-build/PushPlugin) , then I found phonegap-push-plugin from [here](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/EXAMPLES.md)  

I followed instructions and I genereate a template with push.js file 
`/* global cordova:false */
/* globals window */

/*!
 * Module dependencies.
 */

var exec = cordova.require('cordova/exec');

/**
 * PushNotification constructor.
 *
 * @param {Object} options to initiate Push Notifications.
 * @return {PushNotification} instance that can be monitored and cancelled.
 */

var PushNotification = function(options) {
    this._handlers = {
        'registration': [],
        'notification': [],
        'error': []
    };

    // require options parameter
    if (typeof options === 'undefined') {
        throw new Error('The options argument is required.');
    }

    // store the options to this object instance
    this.options = options;

    // triggered on registration and notification
    var that = this;
    var success = function(result) {
        if (result && typeof result.registrationId !== 'undefined') {
            that.emit('registration', result);
        } else if (result && result.additionalData && typeof result.additionalData.actionCallback !== 'undefined') {
            var executeFunctionByName = function(functionName, context /*, args */) {
                var args = Array.prototype.slice.call(arguments, 2);
                var namespaces = functionName.split('.');
                var func = namespaces.pop();
                for (var i = 0; i < namespaces.length; i++) {
                    context = context[namespaces[i]];
                }
                return context[func].apply(context, args);
            };

            executeFunctionByName(result.additionalData.actionCallback, window, result);
        } else if (result) {
            that.emit('notification', result);
        }
    };

    // triggered on error
    var fail = function(msg) {
        var e = (typeof msg === 'string') ? new Error(msg) : msg;
        that.emit('error', e);
    };

    // wait at least one process tick to allow event subscriptions
    setTimeout(function() {
        exec(success, fail, 'PushNotification', 'init', [options]);
    }, 10);
};

/**
 * Unregister from push notifications
 */

PushNotification.prototype.unregister = function(successCallback, errorCallback, options) {
    if (!errorCallback) { errorCallback = function() {}; }

    if (typeof errorCallback !== 'function')  {
        console.log('PushNotification.unregister failure: failure parameter not a function');
        return;
    }

    if (typeof successCallback !== 'function') {
        console.log('PushNotification.unregister failure: success callback parameter must be a function');
        return;
    }

    var that = this;
    var cleanHandlersAndPassThrough = function() {
        if (!options) {
            that._handlers = {
                'registration': [],
                'notification': [],
                'error': []
            };
        }
        successCallback();
    };

    exec(cleanHandlersAndPassThrough, errorCallback, 'PushNotification', 'unregister', [options]);
};

/**
 * Call this to set the application icon badge
 */

PushNotification.prototype.setApplicationIconBadgeNumber = function(successCallback, errorCallback, badge) {
    if (!errorCallback) { errorCallback = function() {}; }

    if (typeof errorCallback !== 'function')  {
        console.log('PushNotification.setApplicationIconBadgeNumber failure: failure parameter not a function');
        return;
    }

    if (typeof successCallback !== 'function') {
        console.log('PushNotification.setApplicationIconBadgeNumber failure: success callback parameter must be a function');
        return;
    }

    exec(successCallback, errorCallback, 'PushNotification', 'setApplicationIconBadgeNumber', [{badge: badge}]);
};

/**
 * Get the application icon badge
 */

PushNotification.prototype.getApplicationIconBadgeNumber = function(successCallback, errorCallback) {
    if (!errorCallback) { errorCallback = function() {}; }

    if (typeof errorCallback !== 'function')  {
        console.log('PushNotification.getApplicationIconBadgeNumber failure: failure parameter not a function');
        return;
    }

    if (typeof successCallback !== 'function') {
        console.log('PushNotification.getApplicationIconBadgeNumber failure: success callback parameter must be a function');
        return;
    }

    exec(successCallback, errorCallback, 'PushNotification', 'getApplicationIconBadgeNumber', []);
};

/**
 * Get the application icon badge
 */

PushNotification.prototype.clearAllNotifications = function(successCallback, errorCallback) {
    if (!successCallback) { successCallback = function() {}; }
    if (!errorCallback) { errorCallback = function() {}; }

    if (typeof errorCallback !== 'function')  {
        console.log('PushNotification.clearAllNotifications failure: failure parameter not a function');
        return;
    }

    if (typeof successCallback !== 'function') {
        console.log('PushNotification.clearAllNotifications failure: success callback parameter must be a function');
        return;
    }

    exec(successCallback, errorCallback, 'PushNotification', 'clearAllNotifications', []);
};

/**
 * Listen for an event.
 *
 * The following events are supported:
 *
 *   - registration
 *   - notification
 *   - error
 *
 * @param {String} eventName to subscribe to.
 * @param {Function} callback triggered on the event.
 */

PushNotification.prototype.on = function(eventName, callback) {
    if (this._handlers.hasOwnProperty(eventName)) {
        this._handlers[eventName].push(callback);
    }
};

/**
 * Remove event listener.
 *
 * @param {String} eventName to match subscription.
 * @param {Function} handle function associated with event.
 */

PushNotification.prototype.off = function (eventName, handle) {
    if (this._handlers.hasOwnProperty(eventName)) {
        var handleIndex = this._handlers[eventName].indexOf(handle);
        if (handleIndex >= 0) {
            this._handlers[eventName].splice(handleIndex, 1);
        }
    }
};

/**
 * Emit an event.
 *
 * This is intended for internal use only.
 *
 * @param {String} eventName is the event to trigger.
 * @param {*} all arguments are passed to the event listeners.
 *
 * @return {Boolean} is true when the event is triggered otherwise false.
 */

PushNotification.prototype.emit = function() {
    var args = Array.prototype.slice.call(arguments);
    var eventName = args.shift();

    if (!this._handlers.hasOwnProperty(eventName)) {
        return false;
    }

    for (var i = 0, length = this._handlers[eventName].length; i < length; i++) {
        var callback = this._handlers[eventName][i];
        if (typeof callback === 'function') {
            callback.apply(undefined,args);
        } else {
            console.log('event handler: ' + eventName + ' must be a function');
        }
    }

    return true;
};

PushNotification.prototype.finish = function(successCallback, errorCallback, id) {
    if (!successCallback) { successCallback = function() {}; }
    if (!errorCallback) { errorCallback = function() {}; }
    if (!id) { id = 'handler'; }

    if (typeof successCallback !== 'function') {
        console.log('finish failure: success callback parameter must be a function');
        return;
    }

    if (typeof errorCallback !== 'function')  {
        console.log('finish failure: failure parameter not a function');
        return;
    }

    exec(successCallback, errorCallback, 'PushNotification', 'finish', [id]);
};

/*!
 * Push Notification Plugin.
 */

module.exports = {
	
    /**
     * Register for Push Notifications.
     *
     * This method will instantiate a new copy of the PushNotification object
     * and start the registration process.
     *
     * @param {Object} options
     * @return {PushNotification} instance
     */

    init: function(options) {
        return new PushNotification(options);
    },

    hasPermission: function(successCallback, errorCallback) {
        exec(successCallback, errorCallback, 'PushNotification', 'hasPermission', []);
    },

    /**
     * PushNotification Object.
     *
     * Expose the PushNotification object for direct use
     * and testing. Typically, you should use the
     * .init helper method.
     */

    PushNotification: PushNotification
};

`

but it give me module is not defined .. I tried putting 		`if (typeof module != 'undefined' && module.exports) {
			module.exports = PushNotification;
		}`

but it didn't work

=====================

PS: code is working and generating device token , but I want to know what is the effect of "is not a module error "!??

**Comment by chrillewoodz** [comment]
I'm using Angular 2 and trying to get this to work.

```
    this.renderer.listen('document', 'deviceready', () => {

      const push = PushNotification.init({
        android: {
          senderID: '1008311315007'
        },
        ios: {
  
        }
      });

      push.on('registration', (data) => {
        // data.registrationId
        console.log(data);
      });

      push.on('notification', (data) => {
        // data.message,
        // data.title,
        // data.count,
        // data.sound,
        // data.image,
        // data.additionalData
      });

      push.on('error', (e) => {
        // e.message
        console.log(e)
      });
    });
```

But even if I wait for `deviceready` it still says that it's not defined. I've installed all necessary SDK tools etc. but still can't get it to work. Please help.

**Comment by gaurav-chandra** [comment]
+1 for me in ionic 2 push plugin v 2.1.3
