### ISSUE TITLE
GoogleService failed to initialize

### ISSUE THREAD

**Issue by kaynz** [phonegap/phonegap-plugin-push#492]
Hi, getting errors on appstart and on message receiving via gcm on my android phone

Here's a paste of the logcat output: http://pastebin.com/26wuaCqi
I've got following in my manifest:

    <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" tools:replace="android:value" />

**Comment by macdonst** [comment]
@kaynz is that causing any problems in your app or is it just a warning?

**Comment by kaynz** [comment]
It's red (Log.e()), so it's meant be an error. Actually I'm debugging some crashes and noticed this error. My app does not crash when the error happens but I'm not sure if it's causing crashes later in app progress.

**Comment by macdonst** [comment]
@kaynz I don't think it will cause a crash but I do think I can fix it.

**Comment by kaynz** [comment]
@macdonst thanks! =)

**Comment by macdonst** [comment]
@kaynz I checked in the fix to the v1.6.x branch. I've fixed it so you no longer get the error log but there is no problem caused by this that I can find.

**Comment by kaynz** [comment]
Thanks, great! :)

**Comment by kaynz** [comment]
Hi @macdonst,

did you try this out?

Still getting the error.

My config looks like this:

    <plugin name="phonegap-plugin-push" spec="~1.5.3">
        <variable name="SENDER_ID" value="#projectNumber"/>
    </plugin>

**Comment by macdonst** [comment]
@kaynz I didn't release the fix yet. It slightly changes the way you setup the plugin so I wanted to include it in the upcoming 1.6.0 release.
